const { Router } = require('express');
const getFriend = require('./getFriend');
const saveFriend = require('./saveFriend');
const deleteFriend = require('./deleteFriend');
const router = Router();
// const filter = { password: 0, _v: 0 };
module.exports = router;
router.get('/list', getFriend);
router.post('/save', saveFriend);
router.post('/delete', deleteFriend);
