const { Router } = require('express');
const getArticle = require('./getArticle');
const saveArticle = require('./saveArticle');
const deleteArticle = require('./deleteArticle');
const changeArticleStatus = require('./changeArticleStatus');
const router = Router();
// const filter = { password: 0, _v: 0 };
module.exports = router;
router.get('/list', getArticle);
router.post('/save', saveArticle);
router.post('/delete', deleteArticle);
router.post('/changeStatus', changeArticleStatus);
