const { Router } = require('express');
const getResource = require('./getResource');
const saveResource = require('./saveResource');
const deleteResource = require('./deleteResource');
const router = Router();
// const filter = { password: 0, _v: 0 };
module.exports = router;
router.get('/list', getResource);
router.post('/save', saveResource);
router.post('/delete', deleteResource);
